name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          npm ci
          npm test
  test-demo-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          cd demo
          npm ci
          npm run build