name: test

on:
  push:
    paths-ignore:
      - README.md
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test lib
        run: |
          npm ci
          npm test
  test-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test demo
        run: |
          npm ci
          npm run build
          cd demo
          npm ci
          npm run build
          npm test